# Generated by Django 4.0.3 on 2022-03-17 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devices_network', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='actuators',
        ),
        migrations.RemoveField(
            model_name='device',
            name='sensors',
        ),
        migrations.AddField(
            model_name='actuator',
            name='device',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='devices_network.device'),
        ),
        migrations.AddField(
            model_name='sensor',
            name='device',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='devices_network.device'),
        ),
    ]
