# Generated by Django 4.0.3 on 2022-03-20 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devices_network', '0002_remove_device_actuators_remove_device_sensors_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='device',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='sensors', to='devices_network.device'),
        ),
    ]
