# Generated by Django 4.0.3 on 2022-04-02 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devices_network', '0003_alter_sensor_device'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actuator',
            name='device',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='actuators', to='devices_network.device'),
        ),
        migrations.AlterField(
            model_name='actuator',
            name='name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='name',
            field=models.CharField(max_length=128),
        ),
    ]
